name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Install Node.js modules
      run: npm ci

    - name: Compile
      run: npm run compile

    - name: Lint
      run: npm run lint

    - name: Test
      run: DISPLAY=:99 npm test
