name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Install Node.js modules
      run: npm ci

    - name: Compile
      run: npm run compile

    - name: Lint
      run: npm run lint

    - name: Test
      run: DISPLAY=:99 npm test
